// ============================================================
// RUGBY HYBRID XV DRAFT — DATA FILE
// 2023 Rugby World Cup squads, pools, and tournament structure
//
// Each player has:
//   name          — display name
//   positions     — array of recognised positions (no penalty).
//                   First entry is their primary position.
//   num           — squad number
//   rating        — quality at RWC 2023
//   careerRating  — personal peak rating across career
//
// Position values used:
//   "Loosehead Prop", "Tighthead Prop", "Hooker",
//   "Lock", "Blindside Flanker", "Openside Flanker", "Number 8",
//   "Scrum-half", "Fly-half",
//   "Inside Centre", "Outside Centre",
//   "Left Wing", "Right Wing", "Fullback"
// ============================================================

function getFlagEmbed(country) {
    const isoMap = {
        "England":"gb-eng","Wales":"gb-wls","Scotland":"gb-sct","Ireland":"ie",
        "France":"fr","Italy":"it","New Zealand":"nz","South Africa":"za",
        "Australia":"au","Argentina":"ar","Japan":"jp","Fiji":"fj",
        "Samoa":"ws","Tonga":"to","Georgia":"ge","Romania":"ro",
        "Uruguay":"uy","Namibia":"na","Portugal":"pt","Chile":"cl"
    };
    const code = isoMap[country];
    return code
        ? `<img src="https://flagcdn.com/w40/${code}.png" alt="${country}" style="width:32px;vertical-align:middle;border-radius:2px;border:1px solid rgba(255,255,255,0.15);">`
        : `<span style="font-size:1.8rem;">🏳️</span>`;
}

// ============================================================
// 2023 RWC TOURNAMENT STRUCTURE
// ============================================================
const rwc2023PoolStandings = {
    A: ["France","New Zealand","Italy","Uruguay","Namibia"],
    B: ["Ireland","South Africa","Scotland","Tonga","Romania"],
    C: ["Wales","Fiji","Australia","Georgia","Portugal"],
    D: ["England","Argentina","Japan","Samoa","Chile"]
};

// All pool-stage results: [team1, score1, score2, team2]
const rwc2023PoolResults = [
    // Pool A
    ["France",27,13,"New Zealand"],
    ["Italy",52,8,"Namibia"],
    ["France",27,12,"Uruguay"],
    ["New Zealand",71,3,"Namibia"],
    ["Italy",38,17,"Uruguay"],
    ["France",96,0,"Namibia"],
    ["New Zealand",96,17,"Italy"],
    ["Uruguay",36,26,"Namibia"],
    ["France",60,7,"Italy"],
    ["New Zealand",73,0,"Uruguay"],
    // Pool B
    ["Ireland",82,8,"Romania"],
    ["South Africa",18,3,"Scotland"],
    ["Ireland",59,16,"Tonga"],
    ["South Africa",76,0,"Romania"],
    ["Ireland",13,8,"South Africa"],
    ["Scotland",45,17,"Tonga"],
    ["South Africa",49,18,"Tonga"],
    ["Ireland",36,14,"Scotland"],
    ["Scotland",84,0,"Romania"],
    ["South Africa",26,10,"Tonga"],
    // Pool C
    ["Australia",35,15,"Georgia"],
    ["Wales",32,26,"Fiji"],
    ["Wales",28,8,"Portugal"],
    ["Australia",15,22,"Fiji"],
    ["Georgia",18,18,"Portugal"],
    ["Wales",40,6,"Australia"],
    ["Fiji",45,12,"Georgia"],
    ["Portugal",24,23,"Fiji"],
    ["Wales",43,19,"Georgia"],
    ["Australia",34,14,"Portugal"],
    // Pool D
    ["England",27,10,"Argentina"],
    ["Japan",42,12,"Chile"],
    ["England",34,12,"Japan"],
    ["Argentina",73,0,"Chile"],
    ["England",71,0,"Chile"],
    ["Argentina",19,10,"Samoa"],
    ["Japan",28,22,"Samoa"],
    ["England",18,17,"Samoa"],
    ["Argentina",29,12,"Japan"],
    ["Samoa",43,10,"Chile"]
];

// Actual 2023 pool points (used to calibrate simulation)
const rwc2023ActualPoints = {
    A: {"France":18,"New Zealand":15,"Italy":10,"Uruguay":5,"Namibia":0},
    B: {"Ireland":19,"South Africa":15,"Scotland":10,"Tonga":5,"Romania":0},
    C: {"Wales":16,"Fiji":15,"Australia":8,"Portugal":6,"Georgia":5},
    D: {"England":16,"Argentina":15,"Japan":12,"Samoa":8,"Chile":0}
};

// Team strength ratings — 2023 tournament form
const teamStrengths = {
    "France":91,"New Zealand":90,"South Africa":93,"Ireland":92,
    "England":85,"Argentina":84,"Wales":80,"Fiji":82,
    "Australia":79,"Scotland":81,"Italy":76,"Japan":74,
    "Samoa":71,"Georgia":68,"Uruguay":66,"Tonga":65,
    "Portugal":64,"Romania":58,"Namibia":54,"Chile":52
};

// ============================================================
// SQUAD DATA
// ============================================================
const rwc2023Squads = {

    "France": [
        { name:"C. Baille",         positions:["Loosehead Prop"],                          num:1,  rating:88, careerRating:88 },
        { name:"J. Marchand",       positions:["Hooker"],                                  num:2,  rating:91, careerRating:91 },
        { name:"U. Atonio",         positions:["Tighthead Prop"],                          num:3,  rating:87, careerRating:88 },
        { name:"T. Flament",        positions:["Lock"],                                    num:4,  rating:85, careerRating:85 },
        { name:"C. Willemse",       positions:["Lock"],                                    num:5,  rating:83, careerRating:84 },
        { name:"F. Cros",           positions:["Blindside Flanker","Openside Flanker"],    num:6,  rating:85, careerRating:85 },
        { name:"C. Ollivon",        positions:["Openside Flanker","Blindside Flanker"],    num:7,  rating:87, careerRating:87 },
        { name:"G. Alldritt",       positions:["Number 8","Blindside Flanker"],            num:8,  rating:92, careerRating:92 },
        { name:"A. Dupont",         positions:["Scrum-half"],                              num:9,  rating:98, careerRating:98 },
        { name:"M. Jalibert",       positions:["Fly-half"],                                num:10, rating:87, careerRating:87 },
        { name:"G. Villiere",       positions:["Left Wing","Right Wing","Fullback"],       num:11, rating:82, careerRating:82 },
        { name:"G. Fickou",         positions:["Inside Centre","Outside Centre"],          num:12, rating:88, careerRating:88 },
        { name:"J. Danty",          positions:["Inside Centre","Outside Centre"],          num:13, rating:84, careerRating:84 },
        { name:"D. Penaud",         positions:["Right Wing","Left Wing"],                  num:14, rating:89, careerRating:89 },
        { name:"T. Ramos",          positions:["Fullback","Right Wing","Fly-half"],        num:15, rating:86, careerRating:86 },
        { name:"P. Mauvaka",        positions:["Hooker"],                                  num:16, rating:84, careerRating:84 },
        { name:"S. Falatea",        positions:["Loosehead Prop","Tighthead Prop"],         num:17, rating:81, careerRating:81 },
        { name:"D. Aldegheri",      positions:["Tighthead Prop"],                          num:18, rating:80, careerRating:80 },
        { name:"P. Woki",           positions:["Lock","Blindside Flanker"],                num:19, rating:82, careerRating:82 },
        { name:"A. Jelonch",        positions:["Blindside Flanker","Number 8"],            num:20, rating:81, careerRating:81 },
        { name:"M. Lucu",           positions:["Scrum-half"],                              num:21, rating:79, careerRating:79 },
        { name:"A. Hastoy",         positions:["Fly-half"],                                num:22, rating:80, careerRating:80 },
        { name:"L. Bielle-Biarrey", positions:["Right Wing","Left Wing"],                  num:23, rating:83, careerRating:83 }
    ],

    "New Zealand": [
        { name:"E. de Groot",   positions:["Loosehead Prop"],                          num:1,  rating:84, careerRating:84 },
        { name:"C. Taylor",     positions:["Hooker"],                                  num:2,  rating:88, careerRating:89 },
        { name:"N. Laulala",    positions:["Tighthead Prop"],                          num:3,  rating:85, careerRating:86 },
        { name:"B. Retallick",  positions:["Lock"],                                    num:4,  rating:90, careerRating:95 },
        { name:"S. Whitelock",  positions:["Lock"],                                    num:5,  rating:91, careerRating:93 },
        { name:"S. Cane",       positions:["Openside Flanker","Blindside Flanker"],    num:6,  rating:86, careerRating:88 },
        { name:"D. Papalii",    positions:["Openside Flanker","Blindside Flanker","Number 8"], num:7, rating:84, careerRating:84 },
        { name:"A. Savea",      positions:["Number 8","Blindside Flanker"],            num:8,  rating:92, careerRating:93 },
        { name:"A. Smith",      positions:["Scrum-half"],                              num:9,  rating:90, careerRating:92 },
        { name:"R. Mo'unga",    positions:["Fly-half"],                                num:10, rating:91, careerRating:91 },
        { name:"M. Telea",      positions:["Right Wing","Fullback"],                   num:11, rating:84, careerRating:84 },
        { name:"J. Barrett",    positions:["Inside Centre","Outside Centre","Fly-half","Fullback"], num:12, rating:88, careerRating:89 },
        { name:"R. Ioane",      positions:["Outside Centre","Inside Centre","Left Wing"], num:13, rating:85, careerRating:86 },
        { name:"W. Jordan",     positions:["Right Wing","Fullback"],                   num:14, rating:90, careerRating:90 },
        { name:"B. Barrett",    positions:["Fullback","Fly-half","Left Wing"],         num:15, rating:93, careerRating:95 },
        { name:"D. Coles",      positions:["Hooker"],                                  num:16, rating:86, careerRating:88 },
        { name:"T. Williams",   positions:["Loosehead Prop"],                          num:17, rating:81, careerRating:81 },
        { name:"T. Lomax",      positions:["Tighthead Prop"],                          num:18, rating:82, careerRating:82 },
        { name:"T. Vaa'i",      positions:["Lock"],                                    num:19, rating:82, careerRating:82 },
        { name:"L. Jacobson",   positions:["Number 8","Blindside Flanker"],            num:20, rating:81, careerRating:81 },
        { name:"F. Christie",   positions:["Scrum-half"],                              num:21, rating:80, careerRating:80 },
        { name:"D. McKenzie",   positions:["Fly-half","Fullback"],                     num:22, rating:83, careerRating:84 },
        { name:"C. Clarke",     positions:["Left Wing","Fullback"],                    num:23, rating:82, careerRating:82 }
    ],

    "South Africa": [
        { name:"S. Kitshoff",       positions:["Loosehead Prop"],                          num:1,  rating:88, careerRating:90 },
        { name:"B. Mbonambi",       positions:["Hooker"],                                  num:2,  rating:87, careerRating:88 },
        { name:"F. Malherbe",       positions:["Tighthead Prop","Loosehead Prop"],         num:3,  rating:88, careerRating:89 },
        { name:"E. Etzebeth",       positions:["Lock"],                                    num:4,  rating:92, careerRating:93 },
        { name:"F. Mostert",        positions:["Lock","Blindside Flanker"],                num:5,  rating:87, careerRating:88 },
        { name:"S. Kolisi",         positions:["Blindside Flanker","Openside Flanker"],    num:6,  rating:89, careerRating:90 },
        { name:"P.S. du Toit",      positions:["Openside Flanker","Blindside Flanker","Lock"], num:7, rating:93, careerRating:94 },
        { name:"D. Vermeulen",      positions:["Number 8","Blindside Flanker"],            num:8,  rating:88, careerRating:90 },
        { name:"F. de Klerk",       positions:["Scrum-half"],                              num:9,  rating:86, careerRating:87 },
        { name:"H. Pollard",        positions:["Fly-half"],                                num:10, rating:87, careerRating:88 },
        { name:"K. Arendse",        positions:["Right Wing","Fullback"],                   num:11, rating:84, careerRating:84 },
        { name:"D. de Allende",     positions:["Inside Centre","Outside Centre"],          num:12, rating:87, careerRating:88 },
        { name:"L. Am",             positions:["Outside Centre","Inside Centre"],          num:13, rating:84, careerRating:85 },
        { name:"C. Kolbe",          positions:["Right Wing","Fullback"],                   num:14, rating:91, careerRating:92 },
        { name:"W. le Roux",        positions:["Fullback","Right Wing"],                   num:15, rating:87, careerRating:89 },
        { name:"M. Marx",           positions:["Hooker"],                                  num:16, rating:88, careerRating:90 },
        { name:"O. Nche",           positions:["Loosehead Prop","Tighthead Prop"],         num:17, rating:82, careerRating:83 },
        { name:"T. Nyakane",        positions:["Tighthead Prop","Loosehead Prop"],         num:18, rating:83, careerRating:85 },
        { name:"L. de Jager",       positions:["Lock"],                                    num:19, rating:84, careerRating:86 },
        { name:"M. van der Merwe",  positions:["Blindside Flanker","Number 8"],            num:20, rating:80, careerRating:80 },
        { name:"C. Reinach",        positions:["Scrum-half"],                              num:21, rating:83, careerRating:84 },
        { name:"M. Libbok",         positions:["Fly-half","Fullback"],                     num:22, rating:82, careerRating:82 },
        { name:"D. Willemse",       positions:["Fullback","Outside Centre"],               num:23, rating:81, careerRating:82 }
    ],

    "Ireland": [
        { name:"A. Porter",        positions:["Loosehead Prop"],                           num:1,  rating:88, careerRating:89 },
        { name:"D. Sheehan",       positions:["Hooker"],                                   num:2,  rating:87, careerRating:87 },
        { name:"T. Furlong",       positions:["Tighthead Prop"],                           num:3,  rating:93, careerRating:93 },
        { name:"J. Ryan",          positions:["Lock"],                                     num:4,  rating:87, careerRating:87 },
        { name:"T. Beirne",        positions:["Lock","Blindside Flanker","Number 8"],      num:5,  rating:89, careerRating:89 },
        { name:"P. O'Mahony",      positions:["Blindside Flanker","Openside Flanker"],     num:6,  rating:90, careerRating:92 },
        { name:"J. van der Flier", positions:["Openside Flanker","Blindside Flanker"],     num:7,  rating:92, careerRating:92 },
        { name:"C. Doris",         positions:["Number 8","Blindside Flanker"],             num:8,  rating:91, careerRating:91 },
        { name:"J. Gibson-Park",   positions:["Scrum-half"],                               num:9,  rating:87, careerRating:87 },
        { name:"J. Sexton",        positions:["Fly-half"],                                 num:10, rating:91, careerRating:95 },
        { name:"J. Lowe",          positions:["Left Wing","Right Wing","Fullback"],        num:11, rating:84, careerRating:84 },
        { name:"B. Aki",           positions:["Inside Centre","Outside Centre"],           num:12, rating:85, careerRating:86 },
        { name:"G. Ringrose",      positions:["Outside Centre","Inside Centre"],           num:13, rating:88, careerRating:88 },
        { name:"K. Earls",         positions:["Right Wing","Left Wing","Fullback"],        num:14, rating:84, careerRating:88 },
        { name:"H. Keenan",        positions:["Fullback","Right Wing"],                    num:15, rating:85, careerRating:85 },
        { name:"R. Herring",       positions:["Hooker"],                                   num:16, rating:82, careerRating:83 },
        { name:"C. Healy",         positions:["Loosehead Prop"],                           num:17, rating:83, careerRating:87 },
        { name:"F. Bealham",       positions:["Tighthead Prop"],                           num:18, rating:80, careerRating:81 },
        { name:"I. Henderson",     positions:["Lock"],                                     num:19, rating:84, careerRating:87 },
        { name:"R. Baird",         positions:["Openside Flanker","Blindside Flanker","Number 8"], num:20, rating:82, careerRating:82 },
        { name:"C. Murray",        positions:["Scrum-half"],                               num:21, rating:86, careerRating:90 },
        { name:"J. Carbery",       positions:["Fly-half","Fullback"],                      num:22, rating:82, careerRating:83 },
        { name:"M. Hansen",        positions:["Left Wing","Right Wing","Fullback"],        num:23, rating:82, careerRating:82 }
    ],

    "England": [
        { name:"E. Genge",      positions:["Loosehead Prop"],                          num:1,  rating:86, careerRating:87 },
        { name:"J. George",     positions:["Hooker"],                                  num:2,  rating:87, careerRating:87 },
        { name:"D. Cole",       positions:["Tighthead Prop"],                          num:3,  rating:83, careerRating:85 },
        { name:"M. Itoje",      positions:["Lock","Blindside Flanker"],                num:4,  rating:93, careerRating:93 },
        { name:"O. Chessum",    positions:["Lock"],                                    num:5,  rating:82, careerRating:82 },
        { name:"C. Lawes",      positions:["Blindside Flanker","Lock"],                num:6,  rating:85, careerRating:87 },
        { name:"T. Curry",      positions:["Openside Flanker","Blindside Flanker"],    num:7,  rating:88, careerRating:89 },
        { name:"B. Vunipola",   positions:["Number 8"],                                num:8,  rating:85, careerRating:88 },
        { name:"B. Youngs",     positions:["Scrum-half"],                              num:9,  rating:83, careerRating:86 },
        { name:"O. Farrell",    positions:["Fly-half","Inside Centre"],                num:10, rating:87, careerRating:89 },
        { name:"J. May",        positions:["Left Wing","Right Wing"],                  num:11, rating:83, careerRating:87 },
        { name:"O. Lawrence",   positions:["Inside Centre","Outside Centre"],          num:12, rating:82, careerRating:82 },
        { name:"H. Slade",      positions:["Outside Centre","Inside Centre","Fly-half"], num:13, rating:84, careerRating:85 },
        { name:"A. Watson",     positions:["Right Wing","Left Wing","Fullback"],       num:14, rating:84, careerRating:86 },
        { name:"F. Steward",    positions:["Fullback","Right Wing"],                   num:15, rating:83, careerRating:83 },
        { name:"J. Marler",     positions:["Loosehead Prop"],                          num:16, rating:83, careerRating:85 },
        { name:"K. Sinckler",   positions:["Tighthead Prop"],                          num:17, rating:84, careerRating:86 },
        { name:"J. Launchbury", positions:["Lock"],                                    num:18, rating:81, careerRating:85 },
        { name:"B. Earl",       positions:["Number 8","Blindside Flanker","Openside Flanker"], num:19, rating:82, careerRating:82 },
        { name:"S. Underhill",  positions:["Openside Flanker","Blindside Flanker"],    num:20, rating:85, careerRating:86 },
        { name:"A. Mitchell",   positions:["Scrum-half"],                              num:21, rating:80, careerRating:80 },
        { name:"G. Ford",       positions:["Fly-half","Inside Centre"],                num:22, rating:85, careerRating:87 },
        { name:"E. Daly",       positions:["Fullback","Right Wing","Left Wing"],       num:23, rating:81, careerRating:84 }
    ],

    "Argentina": [
        { name:"T. Gallo",          positions:["Loosehead Prop"],                          num:1,  rating:83, careerRating:84 },
        { name:"J. Montoya",        positions:["Hooker"],                                  num:2,  rating:86, careerRating:87 },
        { name:"F. Gomez Kodela",   positions:["Tighthead Prop"],                          num:3,  rating:80, careerRating:81 },
        { name:"M. Alemanno",       positions:["Lock"],                                    num:4,  rating:82, careerRating:83 },
        { name:"G. Petti",          positions:["Lock","Blindside Flanker"],                num:5,  rating:83, careerRating:84 },
        { name:"P. Matera",         positions:["Blindside Flanker","Openside Flanker"],    num:6,  rating:87, careerRating:88 },
        { name:"M. Kremer",         positions:["Openside Flanker","Blindside Flanker"],    num:7,  rating:83, careerRating:84 },
        { name:"J.M. Gonzalez",     positions:["Number 8","Blindside Flanker"],            num:8,  rating:84, careerRating:85 },
        { name:"G. Bertranou",      positions:["Scrum-half"],                              num:9,  rating:80, careerRating:81 },
        { name:"S. Carreras",       positions:["Fly-half","Fullback"],                     num:10, rating:83, careerRating:83 },
        { name:"B. Delguy",         positions:["Right Wing","Left Wing"],                  num:11, rating:83, careerRating:84 },
        { name:"J. de la Fuente",   positions:["Outside Centre","Inside Centre"],          num:12, rating:83, careerRating:84 },
        { name:"M. Moroni",         positions:["Outside Centre","Inside Centre"],          num:13, rating:81, careerRating:82 },
        { name:"E. Mallia",         positions:["Right Wing","Left Wing","Fullback"],       num:14, rating:82, careerRating:82 },
        { name:"J. Tuculet",        positions:["Fullback","Right Wing"],                   num:15, rating:82, careerRating:84 },
        { name:"A. Creevy",         positions:["Hooker"],                                  num:16, rating:80, careerRating:82 },
        { name:"M. Vivas",          positions:["Loosehead Prop"],                          num:17, rating:79, careerRating:80 },
        { name:"E. Bello",          positions:["Tighthead Prop"],                          num:18, rating:79, careerRating:80 },
        { name:"T. Lavanini",       positions:["Lock"],                                    num:19, rating:81, careerRating:82 },
        { name:"F. Isa",            positions:["Blindside Flanker","Number 8"],            num:20, rating:79, careerRating:81 },
        { name:"T. Cubelli",        positions:["Scrum-half"],                              num:21, rating:82, careerRating:83 },
        { name:"N. Sanchez",        positions:["Fly-half"],                                num:22, rating:83, careerRating:87 },
        { name:"J.C. Mallia",       positions:["Fullback","Outside Centre"],               num:23, rating:81, careerRating:81 }
    ],

    "Wales": [
        { name:"G. Thomas",     positions:["Loosehead Prop"],                          num:1,  rating:81, careerRating:82 },
        { name:"D. Lake",       positions:["Hooker"],                                  num:2,  rating:81, careerRating:81 },
        { name:"T. Francis",    positions:["Tighthead Prop"],                          num:3,  rating:80, careerRating:81 },
        { name:"A.W. Jones",    positions:["Lock"],                                    num:4,  rating:84, careerRating:88 },
        { name:"A. Beard",      positions:["Lock"],                                    num:5,  rating:81, careerRating:82 },
        { name:"J. Morgan",     positions:["Openside Flanker","Blindside Flanker"],    num:6,  rating:83, careerRating:83 },
        { name:"J. Tipuric",    positions:["Openside Flanker","Blindside Flanker"],    num:7,  rating:86, careerRating:87 },
        { name:"T. Faletau",    positions:["Number 8","Blindside Flanker"],            num:8,  rating:85, careerRating:88 },
        { name:"T. Williams",   positions:["Scrum-half"],                              num:9,  rating:82, careerRating:83 },
        { name:"D. Biggar",     positions:["Fly-half"],                                num:10, rating:83, careerRating:86 },
        { name:"L. Williams",   positions:["Left Wing","Right Wing","Fullback"],       num:11, rating:81, careerRating:83 },
        { name:"J. Davies",     positions:["Inside Centre","Outside Centre"],          num:12, rating:83, careerRating:85 },
        { name:"G. North",      positions:["Outside Centre","Inside Centre","Left Wing","Right Wing"], num:13, rating:83, careerRating:88 },
        { name:"J. Adams",      positions:["Right Wing","Left Wing"],                  num:14, rating:84, careerRating:85 },
        { name:"L. Halfpenny",  positions:["Fullback","Right Wing"],                   num:15, rating:84, careerRating:89 },
        { name:"K. Owens",      positions:["Hooker"],                                  num:16, rating:81, careerRating:83 },
        { name:"R. Jones",      positions:["Loosehead Prop"],                          num:17, rating:78, careerRating:79 },
        { name:"D. Lewis",      positions:["Tighthead Prop","Loosehead Prop"],         num:18, rating:78, careerRating:78 },
        { name:"W. Jones",      positions:["Lock"],                                    num:19, rating:79, careerRating:80 },
        { name:"C. Tshiunza",   positions:["Blindside Flanker","Lock"],                num:20, rating:80, careerRating:80 },
        { name:"G. Davies",     positions:["Scrum-half"],                              num:21, rating:80, careerRating:82 },
        { name:"O. Williams",   positions:["Fly-half","Inside Centre"],                num:22, rating:79, careerRating:80 },
        { name:"O. Watkin",     positions:["Outside Centre","Inside Centre","Right Wing"], num:23, rating:79, careerRating:81 }
    ],

    "Fiji": [
        { name:"E. Mawi",           positions:["Loosehead Prop"],                          num:1,  rating:82, careerRating:82 },
        { name:"T. Ikanivere",      positions:["Hooker"],                                  num:2,  rating:82, careerRating:82 },
        { name:"P. Ravai",          positions:["Tighthead Prop"],                          num:3,  rating:82, careerRating:83 },
        { name:"I. Nasilasila",     positions:["Lock"],                                    num:4,  rating:80, careerRating:80 },
        { name:"T. Cirikidaveta",   positions:["Lock","Blindside Flanker"],                num:5,  rating:80, careerRating:80 },
        { name:"L. Botia",          positions:["Blindside Flanker","Number 8","Lock"],     num:6,  rating:85, careerRating:86 },
        { name:"A. Tuisue",         positions:["Number 8","Blindside Flanker"],            num:7,  rating:83, careerRating:83 },
        { name:"V. Mata",           positions:["Number 8","Blindside Flanker"],            num:8,  rating:86, careerRating:87 },
        { name:"F. Lomani",         positions:["Scrum-half"],                              num:9,  rating:83, careerRating:83 },
        { name:"V. Muntz",          positions:["Fly-half"],                                num:10, rating:79, careerRating:80 },
        { name:"J. Tuisova",        positions:["Left Wing","Right Wing","Outside Centre"], num:11, rating:86, careerRating:87 },
        { name:"W. Nayacalevu",     positions:["Inside Centre","Outside Centre"],          num:12, rating:84, careerRating:84 },
        { name:"S. Radradra",       positions:["Outside Centre","Inside Centre","Left Wing","Right Wing"], num:13, rating:90, careerRating:91 },
        { name:"S. Habosi",         positions:["Right Wing","Left Wing"],                  num:14, rating:80, careerRating:80 },
        { name:"I. Droasese",       positions:["Fullback","Right Wing"],                   num:15, rating:81, careerRating:81 },
        { name:"S. Matavesi",       positions:["Hooker"],                                  num:16, rating:79, careerRating:80 },
        { name:"L. Tagi",           positions:["Loosehead Prop"],                          num:17, rating:78, careerRating:78 },
        { name:"J. Koroiduadua",    positions:["Tighthead Prop","Loosehead Prop"],         num:18, rating:78, careerRating:78 },
        { name:"M. Derenalagi",     positions:["Lock","Blindside Flanker"],                num:19, rating:79, careerRating:79 },
        { name:"M. Rakodrosese",    positions:["Blindside Flanker","Openside Flanker"],    num:20, rating:79, careerRating:79 },
        { name:"S. Kuruvoli",       positions:["Scrum-half"],                              num:21, rating:77, careerRating:78 },
        { name:"B. Volavola",       positions:["Fly-half","Inside Centre"],                num:22, rating:78, careerRating:79 },
        { name:"V. Tikoisolomone",  positions:["Fullback","Left Wing"],                    num:23, rating:78, careerRating:79 }
    ],

    "Australia": [
        { name:"J. Sio",            positions:["Loosehead Prop"],                          num:1,  rating:82, careerRating:83 },
        { name:"D. Porecki",        positions:["Hooker"],                                  num:2,  rating:80, careerRating:80 },
        { name:"A. Alaalatoa",      positions:["Tighthead Prop"],                          num:3,  rating:83, careerRating:84 },
        { name:"W. Skelton",        positions:["Lock"],                                    num:4,  rating:84, careerRating:85 },
        { name:"R. Arnold",         positions:["Lock"],                                    num:5,  rating:80, careerRating:81 },
        { name:"J. Slipper",        positions:["Blindside Flanker","Loosehead Prop"],      num:6,  rating:80, careerRating:82 },
        { name:"F. McReight",       positions:["Openside Flanker","Blindside Flanker"],    num:7,  rating:80, careerRating:80 },
        { name:"R. Valetini",       positions:["Number 8","Blindside Flanker"],            num:8,  rating:82, careerRating:82 },
        { name:"T. Tate",           positions:["Scrum-half"],                              num:9,  rating:79, careerRating:79 },
        { name:"B. Foley",          positions:["Fly-half"],                                num:10, rating:82, careerRating:85 },
        { name:"M. To'omua",        positions:["Left Wing","Outside Centre","Inside Centre"], num:11, rating:80, careerRating:83 },
        { name:"H. Paisami",        positions:["Inside Centre","Outside Centre"],          num:12, rating:82, careerRating:82 },
        { name:"L. Ikitau",         positions:["Outside Centre","Inside Centre"],          num:13, rating:83, careerRating:83 },
        { name:"M. Hooper",         positions:["Openside Flanker","Blindside Flanker"],    num:14, rating:82, careerRating:87 },
        { name:"A. Kellaway",       positions:["Fullback","Right Wing","Left Wing"],       num:15, rating:81, careerRating:82 },
        { name:"L. Paenga-Amosa",   positions:["Hooker"],                                  num:16, rating:79, careerRating:79 },
        { name:"H. Bell",           positions:["Loosehead Prop"],                          num:17, rating:78, careerRating:78 },
        { name:"S. Tupou",          positions:["Tighthead Prop"],                          num:18, rating:79, careerRating:80 },
        { name:"N. Coleman",        positions:["Lock"],                                    num:19, rating:78, careerRating:78 },
        { name:"N. White",          positions:["Number 8","Openside Flanker","Blindside Flanker"], num:20, rating:78, careerRating:79 },
        { name:"J. Gordon",         positions:["Scrum-half"],                              num:21, rating:77, careerRating:78 },
        { name:"C. Lealiifano",     positions:["Fly-half","Inside Centre"],                num:22, rating:79, careerRating:83 },
        { name:"J. Petaia",         positions:["Fullback","Right Wing","Outside Centre"],  num:23, rating:80, careerRating:80 }
    ],

    "Scotland": [
        { name:"P. Schoeman",   positions:["Loosehead Prop"],                          num:1,  rating:84, careerRating:84 },
        { name:"G. Turner",     positions:["Hooker"],                                  num:2,  rating:83, careerRating:83 },
        { name:"Z. Fagerson",   positions:["Tighthead Prop"],                          num:3,  rating:83, careerRating:84 },
        { name:"S. Cummings",   positions:["Lock"],                                    num:4,  rating:82, careerRating:82 },
        { name:"G. Gilchrist",  positions:["Lock"],                                    num:5,  rating:82, careerRating:82 },
        { name:"J. Ritchie",    positions:["Blindside Flanker","Openside Flanker"],    num:6,  rating:83, careerRating:84 },
        { name:"R. Darge",      positions:["Openside Flanker","Blindside Flanker"],    num:7,  rating:83, careerRating:83 },
        { name:"M. Fagerson",   positions:["Number 8","Blindside Flanker"],            num:8,  rating:82, careerRating:82 },
        { name:"A. Price",      positions:["Scrum-half"],                              num:9,  rating:83, careerRating:83 },
        { name:"F. Russell",    positions:["Fly-half"],                                num:10, rating:89, careerRating:90 },
        { name:"D. van der Merwe", positions:["Left Wing","Right Wing"],               num:11, rating:83, careerRating:84 },
        { name:"S. Tuipulotu",  positions:["Inside Centre","Outside Centre"],          num:12, rating:83, careerRating:83 },
        { name:"H. Jones",      positions:["Outside Centre","Inside Centre"],          num:13, rating:82, careerRating:82 },
        { name:"K. Steyn",      positions:["Right Wing","Left Wing","Fullback"],       num:14, rating:82, careerRating:83 },
        { name:"B. Kinghorn",   positions:["Fullback","Left Wing","Fly-half"],         num:15, rating:82, careerRating:83 },
        { name:"J. Matthews",   positions:["Hooker"],                                  num:16, rating:78, careerRating:79 },
        { name:"A. Dell",       positions:["Loosehead Prop"],                          num:17, rating:80, careerRating:80 },
        { name:"W. Hurd",       positions:["Tighthead Prop"],                          num:18, rating:78, careerRating:78 },
        { name:"R. Gray",       positions:["Lock"],                                    num:19, rating:80, careerRating:82 },
        { name:"L. Crosbie",    positions:["Blindside Flanker","Openside Flanker","Number 8"], num:20, rating:79, careerRating:79 },
        { name:"G. Horne",      positions:["Scrum-half"],                              num:21, rating:79, careerRating:80 },
        { name:"F. Russell",    positions:["Fly-half"],                                num:22, rating:89, careerRating:90 },
        { name:"C. Harris",     positions:["Outside Centre","Inside Centre","Fullback"], num:23, rating:79, careerRating:80 }
    ],

    "Italy": [
        { name:"D. Fischetti",  positions:["Loosehead Prop"],                          num:1,  rating:80, careerRating:81 },
        { name:"G. Nicotera",   positions:["Hooker"],                                  num:2,  rating:78, careerRating:78 },
        { name:"S. Ferrari",    positions:["Tighthead Prop"],                          num:3,  rating:80, careerRating:80 },
        { name:"N. Cannone",    positions:["Lock"],                                    num:4,  rating:79, careerRating:79 },
        { name:"D. Sisi",       positions:["Lock","Blindside Flanker"],                num:5,  rating:80, careerRating:80 },
        { name:"S. Negri",      positions:["Blindside Flanker","Openside Flanker"],    num:6,  rating:80, careerRating:80 },
        { name:"M. Lamaro",     positions:["Openside Flanker","Blindside Flanker","Number 8"], num:7, rating:82, careerRating:82 },
        { name:"L. Cannone",    positions:["Number 8","Blindside Flanker"],            num:8,  rating:80, careerRating:80 },
        { name:"S. Varney",     positions:["Scrum-half"],                              num:9,  rating:79, careerRating:79 },
        { name:"P. Garbisi",    positions:["Fly-half"],                                num:10, rating:82, careerRating:82 },
        { name:"M. Ioane",      positions:["Left Wing","Right Wing"],                  num:11, rating:80, careerRating:80 },
        { name:"L. Morisi",     positions:["Inside Centre","Outside Centre"],          num:12, rating:77, careerRating:78 },
        { name:"J. Brex",       positions:["Outside Centre","Inside Centre"],          num:13, rating:78, careerRating:78 },
        { name:"A. Capuozzo",   positions:["Right Wing","Fullback","Left Wing"],       num:14, rating:83, careerRating:83 },
        { name:"A. Trulla",     positions:["Fullback","Right Wing"],                   num:15, rating:76, careerRating:76 },
        { name:"L. Bigi",       positions:["Hooker"],                                  num:16, rating:77, careerRating:78 },
        { name:"P. Ceccarelli", positions:["Loosehead Prop"],                          num:17, rating:77, careerRating:77 },
        { name:"I. Nemer",      positions:["Tighthead Prop"],                          num:18, rating:76, careerRating:76 },
        { name:"F. Ruzza",      positions:["Lock"],                                    num:19, rating:77, careerRating:77 },
        { name:"M. Zuliani",    positions:["Blindside Flanker","Number 8"],            num:20, rating:75, careerRating:76 },
        { name:"A. Fusco",      positions:["Scrum-half"],                              num:21, rating:74, careerRating:74 },
        { name:"T. Allan",      positions:["Fly-half","Inside Centre"],                num:22, rating:78, careerRating:80 },
        { name:"M. Minozzi",    positions:["Fullback","Right Wing","Left Wing"],       num:23, rating:79, careerRating:80 }
    ],

    "Japan": [
        { name:"K. Inagaki",    positions:["Loosehead Prop"],                          num:1,  rating:80, careerRating:80 },
        { name:"S. Horie",      positions:["Hooker"],                                  num:2,  rating:79, careerRating:80 },
        { name:"J. Moore",      positions:["Tighthead Prop"],                          num:3,  rating:78, careerRating:79 },
        { name:"J. Baille",     positions:["Lock"],                                    num:4,  rating:77, careerRating:77 },
        { name:"W. van der Walt", positions:["Lock"],                                  num:5,  rating:77, careerRating:78 },
        { name:"P. Labuschagne",positions:["Blindside Flanker","Number 8"],            num:6,  rating:79, careerRating:80 },
        { name:"K. Himeno",     positions:["Openside Flanker","Blindside Flanker"],    num:7,  rating:81, careerRating:81 },
        { name:"M. Leitch",     positions:["Number 8","Blindside Flanker","Openside Flanker"], num:8, rating:81, careerRating:83 },
        { name:"Y. Nagare",     positions:["Scrum-half"],                              num:9,  rating:78, careerRating:79 },
        { name:"R. Nakamura",   positions:["Fly-half","Inside Centre"],                num:10, rating:79, careerRating:79 },
        { name:"K. Matsushima", positions:["Right Wing","Left Wing","Fullback"],       num:11, rating:80, careerRating:82 },
        { name:"D. Sione",      positions:["Inside Centre","Outside Centre"],          num:12, rating:75, careerRating:76 },
        { name:"T. Lafaele",    positions:["Outside Centre","Inside Centre"],          num:13, rating:78, careerRating:79 },
        { name:"G. Nagisi",     positions:["Right Wing","Left Wing"],                  num:14, rating:76, careerRating:76 },
        { name:"S. Hamamoto",   positions:["Fullback","Right Wing"],                   num:15, rating:76, careerRating:77 },
        { name:"R. Sakate",     positions:["Hooker"],                                  num:16, rating:74, careerRating:74 },
        { name:"K. Asosa",      positions:["Loosehead Prop"],                          num:17, rating:73, careerRating:73 },
        { name:"H. Kizu",       positions:["Tighthead Prop"],                          num:18, rating:73, careerRating:74 },
        { name:"A. Flimmer",    positions:["Lock","Blindside Flanker"],                num:19, rating:73, careerRating:74 },
        { name:"B. Siou",       positions:["Number 8","Blindside Flanker"],            num:20, rating:74, careerRating:74 },
        { name:"T. Kume",       positions:["Scrum-half"],                              num:21, rating:73, careerRating:74 },
        { name:"S. Tanaka",     positions:["Fly-half","Fullback"],                     num:22, rating:74, careerRating:76 },
        { name:"Y. Tamura",     positions:["Fullback","Fly-half"],                     num:23, rating:75, careerRating:76 }
    ],

    "Samoa": [
        { name:"J. Afoa",           positions:["Loosehead Prop","Tighthead Prop"],         num:1,  rating:78, careerRating:80 },
        { name:"S. Tolofua",        positions:["Hooker"],                                  num:2,  rating:76, careerRating:77 },
        { name:"M. Faleolo",        positions:["Tighthead Prop"],                          num:3,  rating:77, careerRating:77 },
        { name:"M. Fidow",          positions:["Lock"],                                    num:4,  rating:75, careerRating:75 },
        { name:"C. Vui",            positions:["Lock"],                                    num:5,  rating:75, careerRating:76 },
        { name:"T. Leiua",          positions:["Blindside Flanker","Number 8"],            num:6,  rating:77, careerRating:78 },
        { name:"F. Sili",           positions:["Openside Flanker","Blindside Flanker"],    num:7,  rating:76, careerRating:77 },
        { name:"S. Sitivi",         positions:["Number 8","Blindside Flanker"],            num:8,  rating:77, careerRating:77 },
        { name:"J. Asoianu",        positions:["Scrum-half"],                              num:9,  rating:75, careerRating:76 },
        { name:"D. Leuila",         positions:["Fly-half"],                                num:10, rating:76, careerRating:77 },
        { name:"B. Ah See",         positions:["Left Wing","Right Wing"],                  num:11, rating:77, careerRating:77 },
        { name:"D. Atama",          positions:["Inside Centre","Outside Centre"],          num:12, rating:75, careerRating:76 },
        { name:"E. Nanai-Williams", positions:["Outside Centre","Inside Centre","Right Wing"], num:13, rating:78, careerRating:79 },
        { name:"S. Tuivailala",     positions:["Right Wing","Left Wing"],                  num:14, rating:76, careerRating:77 },
        { name:"B. Cooper",         positions:["Fullback","Right Wing"],                   num:15, rating:77, careerRating:78 },
        { name:"L. Faaofo",         positions:["Hooker"],                                  num:16, rating:73, careerRating:74 },
        { name:"K. Lealamanu'a",    positions:["Loosehead Prop"],                          num:17, rating:73, careerRating:73 },
        { name:"P. Paulo",          positions:["Tighthead Prop"],                          num:18, rating:73, careerRating:74 },
        { name:"T. Ioane",          positions:["Lock","Blindside Flanker"],                num:19, rating:73, careerRating:74 },
        { name:"S. Fifita",         positions:["Number 8","Blindside Flanker"],            num:20, rating:74, careerRating:75 },
        { name:"G. Stowers",        positions:["Scrum-half"],                              num:21, rating:74, careerRating:75 },
        { name:"C. Lima",           positions:["Fly-half","Inside Centre"],                num:22, rating:74, careerRating:75 },
        { name:"J. Faleolo",        positions:["Fullback","Right Wing"],                   num:23, rating:74, careerRating:74 }
    ],

    "Georgia": [
        { name:"M. Nariashvili",    positions:["Loosehead Prop"],                          num:1,  rating:79, careerRating:80 },
        { name:"S. Mamukashvili",   positions:["Hooker"],                                  num:2,  rating:77, careerRating:77 },
        { name:"D. Zirakashvili",   positions:["Tighthead Prop"],                          num:3,  rating:78, careerRating:79 },
        { name:"K. Mikautadze",     positions:["Lock"],                                    num:4,  rating:76, careerRating:77 },
        { name:"G. Nemsadze",       positions:["Lock"],                                    num:5,  rating:75, careerRating:76 },
        { name:"B. Gorgodze",       positions:["Blindside Flanker","Number 8"],            num:6,  rating:76, careerRating:77 },
        { name:"G. Tkhilaishvili",  positions:["Openside Flanker","Blindside Flanker"],    num:7,  rating:75, careerRating:75 },
        { name:"M. Gorgodze",       positions:["Number 8","Blindside Flanker"],            num:8,  rating:79, careerRating:83 },
        { name:"G. Lobzhanidze",    positions:["Scrum-half"],                              num:9,  rating:76, careerRating:77 },
        { name:"L. Matiashvili",    positions:["Fly-half"],                                num:10, rating:73, careerRating:74 },
        { name:"A. Todua",          positions:["Left Wing","Right Wing"],                  num:11, rating:75, careerRating:75 },
        { name:"D. Kacharava",      positions:["Inside Centre","Outside Centre"],          num:12, rating:74, careerRating:75 },
        { name:"M. Sharikadze",     positions:["Outside Centre","Inside Centre"],          num:13, rating:75, careerRating:76 },
        { name:"A. Gigauri",        positions:["Right Wing","Left Wing"],                  num:14, rating:73, careerRating:74 },
        { name:"S. Tedoradze",      positions:["Fullback","Right Wing"],                   num:15, rating:72, careerRating:73 },
        { name:"V. Karkadze",       positions:["Hooker"],                                  num:16, rating:72, careerRating:72 },
        { name:"G. Chikviladze",    positions:["Loosehead Prop"],                          num:17, rating:71, careerRating:72 },
        { name:"S. Sutiashvili",    positions:["Tighthead Prop"],                          num:18, rating:71, careerRating:72 },
        { name:"L. Chilachava",     positions:["Lock","Blindside Flanker"],                num:19, rating:72, careerRating:73 },
        { name:"G. Tkhilaishvili",  positions:["Blindside Flanker","Openside Flanker"],    num:20, rating:71, careerRating:72 },
        { name:"P. Butkhuzi",       positions:["Scrum-half"],                              num:21, rating:72, careerRating:72 },
        { name:"T. Abzhandadze",    positions:["Fly-half"],                                num:22, rating:73, careerRating:74 },
        { name:"G. Aptsiauri",      positions:["Fullback","Right Wing"],                   num:23, rating:72, careerRating:73 }
    ],

    "Tonga": [
        { name:"S. Taufa",      positions:["Loosehead Prop"],                          num:1,  rating:74, careerRating:74 },
        { name:"E. Taumololo",  positions:["Hooker"],                                  num:2,  rating:73, careerRating:74 },
        { name:"J. Taufa",      positions:["Tighthead Prop"],                          num:3,  rating:74, careerRating:75 },
        { name:"S. Kalamafoni", positions:["Lock","Blindside Flanker"],                num:4,  rating:75, careerRating:76 },
        { name:"T. Lokotui",    positions:["Lock"],                                    num:5,  rating:73, careerRating:74 },
        { name:"V. Fifita",     positions:["Blindside Flanker","Number 8","Lock"],     num:6,  rating:77, careerRating:78 },
        { name:"Z. Lousi",      positions:["Openside Flanker","Blindside Flanker"],    num:7,  rating:74, careerRating:75 },
        { name:"S. Havili",     positions:["Number 8","Blindside Flanker"],            num:8,  rating:75, careerRating:76 },
        { name:"S. Takulua",    positions:["Scrum-half"],                              num:9,  rating:76, careerRating:77 },
        { name:"W. Havili",     positions:["Fly-half","Inside Centre"],                num:10, rating:75, careerRating:76 },
        { name:"D. Lolohea",    positions:["Left Wing","Right Wing","Fly-half"],       num:11, rating:76, careerRating:77 },
        { name:"S. Piutau",     positions:["Inside Centre","Outside Centre","Fly-half"], num:12, rating:79, careerRating:83 },
        { name:"A. Fifita",     positions:["Outside Centre","Inside Centre"],          num:13, rating:76, careerRating:77 },
        { name:"Z. Ngani-Cakobau", positions:["Right Wing","Left Wing"],               num:14, rating:74, careerRating:75 },
        { name:"C. Piutau",     positions:["Fullback","Right Wing","Left Wing"],       num:15, rating:77, careerRating:80 },
        { name:"S. Taumalolo",  positions:["Hooker"],                                  num:16, rating:72, careerRating:73 },
        { name:"K. Pulu",       positions:["Loosehead Prop"],                          num:17, rating:71, careerRating:72 },
        { name:"J. Taulagi",    positions:["Tighthead Prop"],                          num:18, rating:71, careerRating:72 },
        { name:"T. Fifita",     positions:["Lock","Blindside Flanker"],                num:19, rating:72, careerRating:73 },
        { name:"F. Fisi'iahi",  positions:["Number 8","Blindside Flanker"],            num:20, rating:72, careerRating:73 },
        { name:"F. Taufa",      positions:["Scrum-half"],                              num:21, rating:71, careerRating:72 },
        { name:"K. Morath",     positions:["Fly-half"],                                num:22, rating:73, careerRating:74 },
        { name:"V. Lilo",       positions:["Fullback","Left Wing"],                    num:23, rating:72, careerRating:73 }
    ],

    "Romania": [
        { name:"S. Ciuntu",     positions:["Loosehead Prop"],  num:1,  rating:64, careerRating:65 },
        { name:"O. Turashvili", positions:["Hooker"],          num:2,  rating:63, careerRating:64 },
        { name:"E. Balan",      positions:["Tighthead Prop"],  num:3,  rating:63, careerRating:64 },
        { name:"A. Gorin",      positions:["Lock"],            num:4,  rating:62, careerRating:63 },
        { name:"M. Fercu",      positions:["Lock"],            num:5,  rating:62, careerRating:63 },
        { name:"V. Poparlan",   positions:["Blindside Flanker","Number 8"], num:6,  rating:63, careerRating:64 },
        { name:"O. Antonescu",  positions:["Openside Flanker","Blindside Flanker"], num:7, rating:62, careerRating:63 },
        { name:"S. Lama",       positions:["Number 8","Blindside Flanker"], num:8,  rating:63, careerRating:64 },
        { name:"D. Fartusnic",  positions:["Scrum-half"],      num:9,  rating:63, careerRating:64 },
        { name:"F. Vlaicu",     positions:["Fly-half"],        num:10, rating:65, careerRating:67 },
        { name:"E. Dumitru",    positions:["Left Wing","Right Wing"], num:11, rating:62, careerRating:63 },
        { name:"R. Ursache",    positions:["Inside Centre","Outside Centre"], num:12, rating:61, careerRating:62 },
        { name:"C. Lazar",      positions:["Outside Centre","Inside Centre"], num:13, rating:61, careerRating:62 },
        { name:"M. Simionescu", positions:["Right Wing","Left Wing"], num:14, rating:62, careerRating:63 },
        { name:"I. Cazan",      positions:["Fullback"],        num:15, rating:62, careerRating:63 },
        { name:"N. Nedelcu",    positions:["Hooker"],          num:16, rating:60, careerRating:61 },
        { name:"P. Ion",        positions:["Loosehead Prop"],  num:17, rating:60, careerRating:61 },
        { name:"S. Burcea",     positions:["Tighthead Prop"],  num:18, rating:60, careerRating:61 },
        { name:"A. Radoi",      positions:["Lock"],            num:19, rating:60, careerRating:61 },
        { name:"V. Lucaci",     positions:["Number 8","Blindside Flanker"], num:20, rating:60, careerRating:61 },
        { name:"G. Gal",        positions:["Scrum-half"],      num:21, rating:60, careerRating:61 },
        { name:"C. Chereches",  positions:["Fly-half"],        num:22, rating:61, careerRating:63 },
        { name:"I. Botezatu",   positions:["Fullback","Right Wing"], num:23, rating:60, careerRating:61 }
    ],

    "Uruguay": [
        { name:"G. Mieres",     positions:["Loosehead Prop"],  num:1,  rating:68, careerRating:69 },
        { name:"G. Dominguez",  positions:["Hooker"],          num:2,  rating:67, careerRating:68 },
        { name:"M. Sanguinetti",positions:["Tighthead Prop"],  num:3,  rating:67, careerRating:68 },
        { name:"G. Kessler",    positions:["Lock"],            num:4,  rating:68, careerRating:69 },
        { name:"J. Rombys",     positions:["Lock"],            num:5,  rating:67, careerRating:68 },
        { name:"I. Dotti",      positions:["Blindside Flanker","Number 8"], num:6, rating:68, careerRating:69 },
        { name:"M. Leindekar",  positions:["Openside Flanker","Blindside Flanker"], num:7, rating:68, careerRating:69 },
        { name:"J.M. Gaminara", positions:["Number 8","Blindside Flanker"], num:8, rating:70, careerRating:71 },
        { name:"S. Arata",      positions:["Scrum-half"],      num:9,  rating:69, careerRating:70 },
        { name:"F. Berchesi",   positions:["Fly-half"],        num:10, rating:70, careerRating:71 },
        { name:"N. Freitas",    positions:["Left Wing","Right Wing"], num:11, rating:68, careerRating:69 },
        { name:"A. Vilaseca",   positions:["Inside Centre","Outside Centre"], num:12, rating:67, careerRating:68 },
        { name:"J. Prada",      positions:["Outside Centre","Inside Centre"], num:13, rating:68, careerRating:69 },
        { name:"G. Mieres Jr.", positions:["Right Wing","Left Wing","Fullback"], num:14, rating:69, careerRating:70 },
        { name:"F. Ormaechea",  positions:["Fullback"],        num:15, rating:70, careerRating:72 },
        { name:"A. Nieto",      positions:["Hooker"],          num:16, rating:65, careerRating:66 },
        { name:"D. Magno",      positions:["Loosehead Prop"],  num:17, rating:64, careerRating:65 },
        { name:"E. Evia",       positions:["Tighthead Prop"],  num:18, rating:64, careerRating:65 },
        { name:"S. Civetta",    positions:["Lock","Blindside Flanker"], num:19, rating:65, careerRating:66 },
        { name:"N. Larrarte",   positions:["Number 8","Blindside Flanker"], num:20, rating:65, careerRating:66 },
        { name:"T. Dagnino",    positions:["Scrum-half"],      num:21, rating:64, careerRating:65 },
        { name:"D. Gaminara",   positions:["Fly-half"],        num:22, rating:65, careerRating:66 },
        { name:"R. Silva",      positions:["Fullback","Right Wing"], num:23, rating:66, careerRating:67 }
    ],

    "Namibia": [
        { name:"H. Redelinghuys",   positions:["Loosehead Prop"],  num:1,  rating:59, careerRating:60 },
        { name:"L. van der Westhuizen", positions:["Hooker"],      num:2,  rating:58, careerRating:59 },
        { name:"O. Louw",           positions:["Tighthead Prop"],  num:3,  rating:58, careerRating:59 },
        { name:"T. van Lill",       positions:["Lock"],            num:4,  rating:58, careerRating:59 },
        { name:"P. du Toit",        positions:["Lock"],            num:5,  rating:59, careerRating:60 },
        { name:"D. Philander",      positions:["Blindside Flanker","Number 8"], num:6, rating:58, careerRating:59 },
        { name:"W. Roets",          positions:["Openside Flanker","Blindside Flanker"], num:7, rating:57, careerRating:58 },
        { name:"D. de la Harpe",    positions:["Number 8","Blindside Flanker"], num:8, rating:60, careerRating:61 },
        { name:"E. Retief",         positions:["Scrum-half"],      num:9,  rating:60, careerRating:61 },
        { name:"P. Kotze",          positions:["Fly-half"],        num:10, rating:62, careerRating:63 },
        { name:"J. Deysel",         positions:["Left Wing","Right Wing"], num:11, rating:60, careerRating:61 },
        { name:"J. van Wyk",        positions:["Inside Centre","Outside Centre"], num:12, rating:58, careerRating:59 },
        { name:"J. Tromp",          positions:["Outside Centre","Inside Centre"], num:13, rating:58, careerRating:59 },
        { name:"C. Botha",          positions:["Right Wing","Left Wing"], num:14, rating:59, careerRating:60 },
        { name:"T. Nambahu",        positions:["Fullback","Right Wing"], num:15, rating:59, careerRating:60 },
        { name:"T. du Plessis",     positions:["Hooker"],          num:16, rating:56, careerRating:57 },
        { name:"C. du Toit",        positions:["Loosehead Prop"],  num:17, rating:55, careerRating:56 },
        { name:"J. Redelinghuys",   positions:["Tighthead Prop"],  num:18, rating:55, careerRating:56 },
        { name:"A. Coetzee",        positions:["Lock","Blindside Flanker"], num:19, rating:56, careerRating:57 },
        { name:"L. Burger",         positions:["Number 8","Blindside Flanker"], num:20, rating:57, careerRating:58 },
        { name:"J. Burger",         positions:["Scrum-half"],      num:21, rating:56, careerRating:57 },
        { name:"T. Forbes",         positions:["Fly-half"],        num:22, rating:57, careerRating:59 },
        { name:"R. van Wyk",        positions:["Fullback","Right Wing"], num:23, rating:57, careerRating:58 }
    ],

    "Portugal": [
        { name:"F. Fernandes",  positions:["Loosehead Prop"],  num:1,  rating:66, careerRating:67 },
        { name:"M. Tadjer",     positions:["Hooker"],          num:2,  rating:66, careerRating:66 },
        { name:"S. Marques",    positions:["Tighthead Prop"],  num:3,  rating:67, careerRating:67 },
        { name:"J. Madeira",    positions:["Lock"],            num:4,  rating:65, careerRating:66 },
        { name:"N. Martins",    positions:["Lock"],            num:5,  rating:65, careerRating:66 },
        { name:"D. Wallis",     positions:["Blindside Flanker","Number 8"], num:6, rating:65, careerRating:66 },
        { name:"J. Granate",    positions:["Openside Flanker","Blindside Flanker"], num:7, rating:64, careerRating:65 },
        { name:"T. Appleton",   positions:["Number 8","Blindside Flanker"], num:8, rating:66, careerRating:67 },
        { name:"J. Lima",       positions:["Scrum-half"],      num:9,  rating:65, careerRating:66 },
        { name:"P. Bettencourt",positions:["Fly-half"],        num:10, rating:66, careerRating:67 },
        { name:"R. Marta",      positions:["Left Wing","Right Wing"], num:11, rating:66, careerRating:67 },
        { name:"N. Sousa Guedes",positions:["Inside Centre","Outside Centre"], num:12, rating:64, careerRating:65 },
        { name:"J. Guedes",     positions:["Outside Centre","Inside Centre"], num:13, rating:64, careerRating:65 },
        { name:"R. Storti",     positions:["Right Wing","Left Wing"], num:14, rating:68, careerRating:69 },
        { name:"S. Pinto",      positions:["Fullback","Right Wing"], num:15, rating:64, careerRating:65 },
        { name:"D. Costa",      positions:["Hooker"],          num:16, rating:62, careerRating:63 },
        { name:"M. Santos",     positions:["Loosehead Prop"],  num:17, rating:62, careerRating:63 },
        { name:"A. Alves",      positions:["Tighthead Prop"],  num:18, rating:62, careerRating:63 },
        { name:"G. Pinto",      positions:["Lock","Blindside Flanker"], num:19, rating:63, careerRating:64 },
        { name:"F. Bruno",      positions:["Number 8","Blindside Flanker"], num:20, rating:62, careerRating:63 },
        { name:"T. Aubry",      positions:["Scrum-half"],      num:21, rating:62, careerRating:63 },
        { name:"M. Cardozo",    positions:["Fly-half","Inside Centre"], num:22, rating:63, careerRating:64 },
        { name:"B. Lopes",      positions:["Fullback","Left Wing"], num:23, rating:62, careerRating:63 }
    ],

    "Chile": [
        { name:"A. Bohme",      positions:["Loosehead Prop"],  num:1,  rating:61, careerRating:62 },
        { name:"T. Dussaillant",positions:["Hooker"],          num:2,  rating:60, careerRating:61 },
        { name:"C. Saavedra",   positions:["Tighthead Prop"],  num:3,  rating:61, careerRating:62 },
        { name:"J.I. Lues",     positions:["Lock"],            num:4,  rating:60, careerRating:61 },
        { name:"I. Inostroza",  positions:["Lock"],            num:5,  rating:59, careerRating:60 },
        { name:"P. Eissmann",   positions:["Blindside Flanker","Number 8"], num:6, rating:60, careerRating:61 },
        { name:"S. Pedrero",    positions:["Openside Flanker","Blindside Flanker"], num:7, rating:59, careerRating:60 },
        { name:"M. Sigren",     positions:["Number 8","Blindside Flanker"], num:8, rating:61, careerRating:62 },
        { name:"S. Videla",     positions:["Scrum-half"],      num:9,  rating:61, careerRating:62 },
        { name:"B. Videla",     positions:["Fly-half"],        num:10, rating:62, careerRating:63 },
        { name:"R. Carvallo",   positions:["Left Wing","Right Wing"], num:11, rating:61, careerRating:62 },
        { name:"M. Garafulic",  positions:["Inside Centre","Outside Centre"], num:12, rating:61, careerRating:62 },
        { name:"S. Fernandez",  positions:["Outside Centre","Inside Centre"], num:13, rating:60, careerRating:61 },
        { name:"J. Larenas",    positions:["Right Wing","Left Wing"], num:14, rating:59, careerRating:60 },
        { name:"I. Ayarza",     positions:["Fullback","Right Wing"], num:15, rating:61, careerRating:62 },
        { name:"R. Martinez",   positions:["Hooker"],          num:16, rating:57, careerRating:58 },
        { name:"I. Orta",       positions:["Loosehead Prop"],  num:17, rating:56, careerRating:57 },
        { name:"B. Soto",       positions:["Tighthead Prop"],  num:18, rating:56, careerRating:57 },
        { name:"T. Elizalde",   positions:["Lock"],            num:19, rating:56, careerRating:57 },
        { name:"E. Gatica",     positions:["Number 8","Blindside Flanker"], num:20, rating:57, careerRating:58 },
        { name:"A. Villagran",  positions:["Scrum-half"],      num:21, rating:56, careerRating:57 },
        { name:"J. Ezcurra",    positions:["Fly-half"],        num:22, rating:57, careerRating:58 },
        { name:"R. Velarde",    positions:["Fullback","Right Wing"], num:23, rating:57, careerRating:58 }
    ]
};

// Position family groupings — maps exact position to display group
const positionFamilyMap = {
    "Loosehead Prop":   "Props",
    "Tighthead Prop":   "Props",
    "Hooker":           "Hookers",
    "Lock":             "Locks",
    "Blindside Flanker":"Back Row",
    "Openside Flanker": "Back Row",
    "Number 8":         "Back Row",
    "Scrum-half":       "Scrum Halves",
    "Fly-half":         "Fly Halves",
    "Inside Centre":    "Centres",
    "Outside Centre":   "Centres",
    "Left Wing":        "Back Three",
    "Right Wing":       "Back Three",
    "Fullback":         "Back Three"
};
